services:
  app:
    build: .
    env_file: .env
    ports:
      - "${PORT:-5050}:5050"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PORT=${PORT}
      - TURN_DETECTION_MODE=${TURN_DETECTION_MODE}
